version: '3.9'

services:
  java_app:
    container_name: java_app
    image: sbpostgdocrest:latest
    build: .
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=root7623
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root7623
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}